[2024-05-19T20:27:10.589+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T20:27:10.611+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2024-05-19T20:27:10.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2024-05-19T20:27:10.622+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T20:27:10.669+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_parquet_files> on 2023-06-12 00:00:00+00:00
[2024-05-19T20:27:10.682+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_s3', 'process_parquet_files', 'scheduled__2023-06-12T00:00:00+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/silver_s3.py', '--cfg-path', '/tmp/tmpvf25jrup']
[2024-05-19T20:27:10.686+0000] {standard_task_runner.py:91} INFO - Job 292: Subtask process_parquet_files
[2024-05-19T20:27:10.685+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=846) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T20:27:10.699+0000] {standard_task_runner.py:63} INFO - Started process 862 to run task
[2024-05-19T20:27:10.775+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_s3.process_parquet_files scheduled__2023-06-12T00:00:00+00:00 [running]> on host 620090466bc8
[2024-05-19T20:27:11.040+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_s3' AIRFLOW_CTX_TASK_ID='process_parquet_files' AIRFLOW_CTX_EXECUTION_DATE='2023-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-12T00:00:00+00:00'
[2024-05-19T20:27:11.055+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T20:27:11.108+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T20:27:11.113+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T20:27:16.781+0000] {logging_mixin.py:188} INFO - No .parquet files found.
[2024-05-19T20:27:16.786+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T20:27:16.804+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T20:27:16.839+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=silver_s3, task_id=process_parquet_files, run_id=scheduled__2023-06-12T00:00:00+00:00, execution_date=20230612T000000, start_date=20240519T202710, end_date=20240519T202716
[2024-05-19T20:27:16.884+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T20:27:16.903+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T20:27:16.905+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-19T20:40:23.260+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T20:40:23.287+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2024-05-19T20:40:23.299+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2024-05-19T20:40:23.301+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T20:40:23.377+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_parquet_files> on 2023-06-12 00:00:00+00:00
[2024-05-19T20:40:23.394+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2590) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T20:40:23.406+0000] {standard_task_runner.py:63} INFO - Started process 2614 to run task
[2024-05-19T20:40:23.409+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_s3', 'process_parquet_files', 'scheduled__2023-06-12T00:00:00+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/silver_s3.py', '--cfg-path', '/tmp/tmpe91b6e06']
[2024-05-19T20:40:23.429+0000] {standard_task_runner.py:91} INFO - Job 409: Subtask process_parquet_files
[2024-05-19T20:40:23.577+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_s3.process_parquet_files scheduled__2023-06-12T00:00:00+00:00 [running]> on host 620090466bc8
[2024-05-19T20:40:23.790+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_s3' AIRFLOW_CTX_TASK_ID='process_parquet_files' AIRFLOW_CTX_EXECUTION_DATE='2023-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-12T00:00:00+00:00'
[2024-05-19T20:40:23.807+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T20:40:23.968+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T20:40:23.981+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T20:40:29.707+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T20:40:29.710+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/silver_s3.py", line 67, in process_parquet_files
    os.remove(file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/disney_data_20240518T000000.parquet'
[2024-05-19T20:40:29.732+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_s3, task_id=process_parquet_files, run_id=scheduled__2023-06-12T00:00:00+00:00, execution_date=20230612T000000, start_date=20240519T204023, end_date=20240519T204029
[2024-05-19T20:40:29.745+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 409 for task process_parquet_files ([Errno 2] No such file or directory: '/tmp/disney_data_20240518T000000.parquet'; 2614)
[2024-05-19T20:40:29.791+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T20:40:29.806+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T20:40:29.808+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
