[2024-05-19T20:26:27.341+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T20:26:27.351+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-20T00:00:00+00:00 [queued]>
[2024-05-19T20:26:27.355+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-20T00:00:00+00:00 [queued]>
[2024-05-19T20:26:27.355+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T20:26:27.362+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_parquet_files> on 2023-04-20 00:00:00+00:00
[2024-05-19T20:26:27.367+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=666) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T20:26:27.369+0000] {standard_task_runner.py:63} INFO - Started process 681 to run task
[2024-05-19T20:26:27.369+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_s3', 'process_parquet_files', 'scheduled__2023-04-20T00:00:00+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/silver_s3.py', '--cfg-path', '/tmp/tmp6p6kwfc8']
[2024-05-19T20:26:27.377+0000] {standard_task_runner.py:91} INFO - Job 239: Subtask process_parquet_files
[2024-05-19T20:26:27.423+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-20T00:00:00+00:00 [running]> on host 620090466bc8
[2024-05-19T20:26:27.470+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_s3' AIRFLOW_CTX_TASK_ID='process_parquet_files' AIRFLOW_CTX_EXECUTION_DATE='2023-04-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-20T00:00:00+00:00'
[2024-05-19T20:26:27.471+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T20:26:27.491+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T20:26:27.491+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T20:26:32.175+0000] {logging_mixin.py:188} INFO - No .parquet files found.
[2024-05-19T20:26:32.176+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T20:26:32.178+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T20:26:32.185+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=silver_s3, task_id=process_parquet_files, run_id=scheduled__2023-04-20T00:00:00+00:00, execution_date=20230420T000000, start_date=20240519T202627, end_date=20240519T202632
[2024-05-19T20:26:32.204+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T20:26:32.215+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T20:26:32.215+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-19T20:31:00.668+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T20:31:00.695+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-20T00:00:00+00:00 [queued]>
[2024-05-19T20:31:00.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-20T00:00:00+00:00 [queued]>
[2024-05-19T20:31:00.708+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T20:31:00.777+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_parquet_files> on 2023-04-20 00:00:00+00:00
[2024-05-19T20:31:00.792+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1068) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T20:31:00.796+0000] {standard_task_runner.py:63} INFO - Started process 1086 to run task
[2024-05-19T20:31:00.798+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_s3', 'process_parquet_files', 'scheduled__2023-04-20T00:00:00+00:00', '--job-id', '338', '--raw', '--subdir', 'DAGS_FOLDER/silver_s3.py', '--cfg-path', '/tmp/tmpmv5f2uvw']
[2024-05-19T20:31:00.809+0000] {standard_task_runner.py:91} INFO - Job 338: Subtask process_parquet_files
[2024-05-19T20:31:00.900+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-20T00:00:00+00:00 [running]> on host 620090466bc8
[2024-05-19T20:31:01.049+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_s3' AIRFLOW_CTX_TASK_ID='process_parquet_files' AIRFLOW_CTX_EXECUTION_DATE='2023-04-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-20T00:00:00+00:00'
[2024-05-19T20:31:01.056+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T20:31:01.085+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T20:31:01.086+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T20:31:31.331+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T20:31:31.339+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/silver_s3.py", line 68, in process_parquet_files
    os.remove(file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/disney_data_20240518T000000.parquet'
[2024-05-19T20:31:31.359+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_s3, task_id=process_parquet_files, run_id=scheduled__2023-04-20T00:00:00+00:00, execution_date=20230420T000000, start_date=20240519T203100, end_date=20240519T203131
[2024-05-19T20:31:31.385+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 338 for task process_parquet_files ([Errno 2] No such file or directory: '/tmp/disney_data_20240518T000000.parquet'; 1086)
[2024-05-19T20:31:31.426+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T20:31:31.438+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T20:31:31.439+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
