[2024-05-19T20:45:03.819+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T20:45:03.825+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: disney_s3.process_and_save_to_s3 scheduled__2024-05-19T20:40:00+00:00 [queued]>
[2024-05-19T20:45:03.828+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: disney_s3.process_and_save_to_s3 scheduled__2024-05-19T20:40:00+00:00 [queued]>
[2024-05-19T20:45:03.828+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-19T20:45:03.833+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_and_save_to_s3> on 2024-05-19 20:40:00+00:00
[2024-05-19T20:45:03.836+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3243) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T20:45:03.837+0000] {standard_task_runner.py:63} INFO - Started process 3245 to run task
[2024-05-19T20:45:03.837+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'disney_s3', 'process_and_save_to_s3', 'scheduled__2024-05-19T20:40:00+00:00', '--job-id', '435', '--raw', '--subdir', 'DAGS_FOLDER/disney_s3.py', '--cfg-path', '/tmp/tmp339q4ym6']
[2024-05-19T20:45:03.839+0000] {standard_task_runner.py:91} INFO - Job 435: Subtask process_and_save_to_s3
[2024-05-19T20:45:03.856+0000] {task_command.py:426} INFO - Running <TaskInstance: disney_s3.process_and_save_to_s3 scheduled__2024-05-19T20:40:00+00:00 [running]> on host 620090466bc8
[2024-05-19T20:45:03.887+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='disney_s3' AIRFLOW_CTX_TASK_ID='process_and_save_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T20:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-19T20:40:00+00:00'
[2024-05-19T20:45:03.888+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T20:45:03.898+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-05-19T20:45:03.929+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T20:45:03.930+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T20:45:07.783+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T20:45:07.785+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T20:45:07.798+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=disney_s3, task_id=process_and_save_to_s3, run_id=scheduled__2024-05-19T20:40:00+00:00, execution_date=20240519T204000, start_date=20240519T204503, end_date=20240519T204507
[2024-05-19T20:45:07.842+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T20:45:07.857+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T20:45:07.858+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
