[2024-05-19T20:26:36.614+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T20:26:36.633+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-29T00:00:00+00:00 [queued]>
[2024-05-19T20:26:36.645+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-29T00:00:00+00:00 [queued]>
[2024-05-19T20:26:36.646+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T20:26:36.662+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_parquet_files> on 2023-04-29 00:00:00+00:00
[2024-05-19T20:26:36.682+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=693) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T20:26:36.684+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_s3', 'process_parquet_files', 'scheduled__2023-04-29T00:00:00+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/silver_s3.py', '--cfg-path', '/tmp/tmp2a0kmhbo']
[2024-05-19T20:26:36.692+0000] {standard_task_runner.py:91} INFO - Job 248: Subtask process_parquet_files
[2024-05-19T20:26:36.691+0000] {standard_task_runner.py:63} INFO - Started process 716 to run task
[2024-05-19T20:26:36.789+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-29T00:00:00+00:00 [running]> on host 620090466bc8
[2024-05-19T20:26:36.939+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_s3' AIRFLOW_CTX_TASK_ID='process_parquet_files' AIRFLOW_CTX_EXECUTION_DATE='2023-04-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-29T00:00:00+00:00'
[2024-05-19T20:26:36.944+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T20:26:36.978+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T20:26:36.980+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T20:26:41.900+0000] {logging_mixin.py:188} INFO - No .parquet files found.
[2024-05-19T20:26:41.901+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T20:26:41.903+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T20:26:41.923+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=silver_s3, task_id=process_parquet_files, run_id=scheduled__2023-04-29T00:00:00+00:00, execution_date=20230429T000000, start_date=20240519T202636, end_date=20240519T202641
[2024-05-19T20:26:41.974+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T20:26:41.984+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T20:26:41.984+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-19T20:31:02.384+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T20:31:02.424+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-29T00:00:00+00:00 [queued]>
[2024-05-19T20:31:02.440+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-29T00:00:00+00:00 [queued]>
[2024-05-19T20:31:02.441+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T20:31:02.454+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_parquet_files> on 2023-04-29 00:00:00+00:00
[2024-05-19T20:31:02.464+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1087) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T20:31:02.469+0000] {standard_task_runner.py:63} INFO - Started process 1109 to run task
[2024-05-19T20:31:02.468+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_s3', 'process_parquet_files', 'scheduled__2023-04-29T00:00:00+00:00', '--job-id', '348', '--raw', '--subdir', 'DAGS_FOLDER/silver_s3.py', '--cfg-path', '/tmp/tmpcl2lkkjt']
[2024-05-19T20:31:02.474+0000] {standard_task_runner.py:91} INFO - Job 348: Subtask process_parquet_files
[2024-05-19T20:31:02.673+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-29T00:00:00+00:00 [running]> on host 620090466bc8
[2024-05-19T20:31:02.873+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_s3' AIRFLOW_CTX_TASK_ID='process_parquet_files' AIRFLOW_CTX_EXECUTION_DATE='2023-04-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-29T00:00:00+00:00'
[2024-05-19T20:31:02.878+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T20:31:02.932+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T20:31:02.934+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T20:31:24.103+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T20:31:24.107+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/silver_s3.py", line 68, in process_parquet_files
    os.remove(file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/disney_data_20240518T000000.parquet'
[2024-05-19T20:31:24.141+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_s3, task_id=process_parquet_files, run_id=scheduled__2023-04-29T00:00:00+00:00, execution_date=20230429T000000, start_date=20240519T203102, end_date=20240519T203124
[2024-05-19T20:31:24.155+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 348 for task process_parquet_files ([Errno 2] No such file or directory: '/tmp/disney_data_20240518T000000.parquet'; 1109)
[2024-05-19T20:31:24.197+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T20:31:24.209+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T20:31:24.210+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
