[2024-05-19T20:26:50.806+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T20:26:50.848+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-05-19T00:00:00+00:00 [queued]>
[2024-05-19T20:26:50.871+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-05-19T00:00:00+00:00 [queued]>
[2024-05-19T20:26:50.872+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T20:26:50.927+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_parquet_files> on 2023-05-19 00:00:00+00:00
[2024-05-19T20:26:50.944+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=757) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T20:26:50.947+0000] {standard_task_runner.py:63} INFO - Started process 780 to run task
[2024-05-19T20:26:50.948+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_s3', 'process_parquet_files', 'scheduled__2023-05-19T00:00:00+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/silver_s3.py', '--cfg-path', '/tmp/tmp_8q0yy83']
[2024-05-19T20:26:50.960+0000] {standard_task_runner.py:91} INFO - Job 268: Subtask process_parquet_files
[2024-05-19T20:26:51.017+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_s3.process_parquet_files scheduled__2023-05-19T00:00:00+00:00 [running]> on host 620090466bc8
[2024-05-19T20:26:51.153+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_s3' AIRFLOW_CTX_TASK_ID='process_parquet_files' AIRFLOW_CTX_EXECUTION_DATE='2023-05-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-19T00:00:00+00:00'
[2024-05-19T20:26:51.157+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T20:26:51.198+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T20:26:51.201+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T20:26:56.049+0000] {logging_mixin.py:188} INFO - No .parquet files found.
[2024-05-19T20:26:56.051+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T20:26:56.052+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T20:26:56.059+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=silver_s3, task_id=process_parquet_files, run_id=scheduled__2023-05-19T00:00:00+00:00, execution_date=20230519T000000, start_date=20240519T202650, end_date=20240519T202656
[2024-05-19T20:26:56.106+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T20:26:56.116+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T20:26:56.117+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-19T20:37:08.404+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T20:37:08.421+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-05-19T00:00:00+00:00 [queued]>
[2024-05-19T20:37:08.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-05-19T00:00:00+00:00 [queued]>
[2024-05-19T20:37:08.433+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T20:37:08.443+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_parquet_files> on 2023-05-19 00:00:00+00:00
[2024-05-19T20:37:08.449+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2039) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T20:37:08.451+0000] {standard_task_runner.py:63} INFO - Started process 2056 to run task
[2024-05-19T20:37:08.454+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_s3', 'process_parquet_files', 'scheduled__2023-05-19T00:00:00+00:00', '--job-id', '384', '--raw', '--subdir', 'DAGS_FOLDER/silver_s3.py', '--cfg-path', '/tmp/tmpg0bd8gfh']
[2024-05-19T20:37:08.458+0000] {standard_task_runner.py:91} INFO - Job 384: Subtask process_parquet_files
[2024-05-19T20:37:08.542+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_s3.process_parquet_files scheduled__2023-05-19T00:00:00+00:00 [running]> on host 620090466bc8
[2024-05-19T20:37:08.652+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_s3' AIRFLOW_CTX_TASK_ID='process_parquet_files' AIRFLOW_CTX_EXECUTION_DATE='2023-05-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-19T00:00:00+00:00'
[2024-05-19T20:37:08.654+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T20:37:08.671+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T20:37:08.673+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T20:37:14.142+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T20:37:14.145+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/silver_s3.py", line 69, in process_parquet_files
    os.remove(file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/disney_data_20240518T000000.parquet'
[2024-05-19T20:37:14.171+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_s3, task_id=process_parquet_files, run_id=scheduled__2023-05-19T00:00:00+00:00, execution_date=20230519T000000, start_date=20240519T203708, end_date=20240519T203714
[2024-05-19T20:37:14.184+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 384 for task process_parquet_files ([Errno 2] No such file or directory: '/tmp/disney_data_20240518T000000.parquet'; 2056)
[2024-05-19T20:37:14.219+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T20:37:14.228+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T20:37:14.229+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
