[2024-05-19T20:26:37.485+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T20:26:37.506+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2024-05-19T20:26:37.521+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2024-05-19T20:26:37.526+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T20:26:37.543+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_parquet_files> on 2023-05-03 00:00:00+00:00
[2024-05-19T20:26:37.554+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=705) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T20:26:37.558+0000] {standard_task_runner.py:63} INFO - Started process 733 to run task
[2024-05-19T20:26:37.558+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_s3', 'process_parquet_files', 'scheduled__2023-05-03T00:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/silver_s3.py', '--cfg-path', '/tmp/tmpt7ego8cc']
[2024-05-19T20:26:37.565+0000] {standard_task_runner.py:91} INFO - Job 252: Subtask process_parquet_files
[2024-05-19T20:26:37.651+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_s3.process_parquet_files scheduled__2023-05-03T00:00:00+00:00 [running]> on host 620090466bc8
[2024-05-19T20:26:37.783+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_s3' AIRFLOW_CTX_TASK_ID='process_parquet_files' AIRFLOW_CTX_EXECUTION_DATE='2023-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-03T00:00:00+00:00'
[2024-05-19T20:26:37.787+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T20:26:37.818+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T20:26:37.819+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T20:26:42.558+0000] {logging_mixin.py:188} INFO - No .parquet files found.
[2024-05-19T20:26:42.561+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T20:26:42.563+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T20:26:42.574+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=silver_s3, task_id=process_parquet_files, run_id=scheduled__2023-05-03T00:00:00+00:00, execution_date=20230503T000000, start_date=20240519T202637, end_date=20240519T202642
[2024-05-19T20:26:42.611+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T20:26:42.623+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T20:26:42.624+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-19T20:31:03.215+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T20:31:03.234+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2024-05-19T20:31:03.238+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2024-05-19T20:31:03.239+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T20:31:03.246+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_parquet_files> on 2023-05-03 00:00:00+00:00
[2024-05-19T20:31:03.251+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1100) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T20:31:03.253+0000] {standard_task_runner.py:63} INFO - Started process 1113 to run task
[2024-05-19T20:31:03.253+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_s3', 'process_parquet_files', 'scheduled__2023-05-03T00:00:00+00:00', '--job-id', '352', '--raw', '--subdir', 'DAGS_FOLDER/silver_s3.py', '--cfg-path', '/tmp/tmpejxcyy0u']
[2024-05-19T20:31:03.256+0000] {standard_task_runner.py:91} INFO - Job 352: Subtask process_parquet_files
[2024-05-19T20:31:03.287+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_s3.process_parquet_files scheduled__2023-05-03T00:00:00+00:00 [running]> on host 620090466bc8
[2024-05-19T20:31:03.341+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_s3' AIRFLOW_CTX_TASK_ID='process_parquet_files' AIRFLOW_CTX_EXECUTION_DATE='2023-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-03T00:00:00+00:00'
[2024-05-19T20:31:03.343+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T20:31:03.356+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T20:31:03.357+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T20:31:24.639+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T20:31:24.642+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/silver_s3.py", line 68, in process_parquet_files
    os.remove(file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/disney_data_20240518T000000.parquet'
[2024-05-19T20:31:24.652+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=silver_s3, task_id=process_parquet_files, run_id=scheduled__2023-05-03T00:00:00+00:00, execution_date=20230503T000000, start_date=20240519T203103, end_date=20240519T203124
[2024-05-19T20:31:24.661+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 352 for task process_parquet_files ([Errno 2] No such file or directory: '/tmp/disney_data_20240518T000000.parquet'; 1113)
[2024-05-19T20:31:24.687+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T20:31:24.700+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T20:31:24.700+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
